# Generated by Django 4.2.8 on 2023-12-18 18:39

import apps.products.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                default=apps.products.models.Category.get_default_category,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="products.category",
            ),
        ),
    ]
