# Generated by Django 4.2.8 on 2023-12-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="size_description",
        ),
        migrations.AddField(
            model_name="image",
            name="size_description",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
