# Generated by Django 4.2.8 on 2023-12-18 19:42

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(
                 to="products.category",
            ),
        ),
    ]
