# Generated by Django 4.2.8 on 2024-01-06 21:41

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_size_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Hide category from the catalog",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                help_text="The name of the category.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent_category",
            field=models.ForeignKey(
                blank=True,
                help_text="id to the parent category for hierarchical structuring.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_categories",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                help_text="Unique slug generated from the category name for URL.",
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="size_description",
            field=models.CharField(
                blank=True,
                help_text="Product size info in the picture",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(
                blank=True, help_text="A description of the product"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Hide product from the catalog",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_archived",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Automatically marked as archived when deleted if referenced by an order",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(
                help_text="The name of the product", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                editable=False,
                help_text="Unique slug generated from the category name for URL.",
                populate_from="name",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_preview",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Sets the image as a preview for the product",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="Hide size for this product from the catalog",
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="price",
            field=models.PositiveIntegerField(
                help_text="The price for this product in this size"
            ),
        ),
        migrations.AlterField(
            model_name="size",
            name="name",
            field=models.CharField(
                help_text="The name of the size.", max_length=50
            ),
        ),
    ]
