# Generated by Django 4.2.8 on 2024-01-11 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0003_alter_category_is_active_alter_category_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="description",
            field=models.TextField(
                blank=True, help_text="A description of the category"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                help_text="Image of the category",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.image",
            ),
        ),
    ]
