# Generated by Django 4.2.8 on 2023-12-19 17:45

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_category_product_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                default=apps.products.models.Category.get_default_category,
                to="products.category",
            ),
        ),
    ]
