# Generated by Django 4.2.8 on 2023-12-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_category_parent_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                through="products.ProductImage",
                to="products.image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_archived",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="product",
            name="size_description",
            field=models.CharField(
                blank=True, default="default", max_length=100
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="sizes",
            field=models.ManyToManyField(
                blank=True, through="products.ProductSize", to="products.size"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="is_preview",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
